'use strict';
const KEY='midiacheck_casos_finais_records',SESSION='midiacheck_casos_finais_session',DATASET='midiacheck-casos-finais';
const $=id=>document.getElementById(id),esc=Scenes.escape;
const labels=['Discordo totalmente','Discordo um pouco','Nem concordo nem discordo','Concordo um pouco','Concordo totalmente'];
const AVATARS=[{icon:'⌕',name:'Investigador'},{icon:'✦',name:'Analista'},{icon:'◇',name:'Guardião'},{icon:'◷',name:'Observador'}];
const LEVELS=[{xp:0,name:'Olhar atento'},{xp:300,name:'Caçador de pistas'},{xp:800,name:'Investigador em ação'},{xp:1400,name:'Analista de contextos'},{xp:2200,name:'Verificador competente'},{xp:3000,name:'Especialista em evidências'},{xp:3600,name:'Guardião da informação'}];
const clone=v=>JSON.parse(JSON.stringify(v));
const style=s=>`--color:${s.color};--pale:${s.pale}`;
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}
function csv(rows){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(';')).join('\r\n')}
const app={
 records:{},student:null,run:null,moduleIndex:0,avatarChoice:0,storageOK:true,sound:false,
 init(){
  this.records={};this.student=null;
  $('hero-case').innerHTML=Scenes.render(QBANK.diagnostic[0].scene);
  $('home-skills').innerHTML=SKILLS.map((s,i)=>`<article class="home-skill" style="${style(s)}"><span class="skill-icon">${s.icon}</span><div><h3>${esc(s.name)}</h3><small>HABILIDADE ${i+1} · 6 CASOS PARA INVESTIGAR</small></div></article>`).join('');
  this.updateSound();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}}));
  const preview=new URLSearchParams(location.search).get('preview');if(preview==='teacher')this.teacher();else if(preview==='student')this.login();else this.home();
 },
 validCode(c){return typeof c==='string'&&/^[A-Z0-9_-]{3,20}$/.test(c)},
 newRecord(code){return{participant_code:code,avatar:this.avatarChoice,xp:0,diagnostic:null,post:null,survey:null,modules:QBANK.modules.map(()=>({answers:{},xp:0})),attempts:[],draft:null,updated_at:new Date().toISOString()}},
 record(){return this.records[this.student]},
 persist(){if(!this.storageOK)return false;try{localStorage.setItem(KEY,JSON.stringify(this.records));return true}catch{this.storageOK=false;this.toast('O navegador não conseguiu salvar. Baixe uma cópia do progresso antes de fechar.');return false}},
 save(r){r.updated_at=new Date().toISOString();this.records[r.participant_code]=r;return this.persist()},
 show(id){if(window.speechSynthesis)window.speechSynthesis.cancel();document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id===id));window.scrollTo({top:0,behavior:'instant'});$('main').focus({preventScroll:true})},
 toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),6000)},
 home(){this.run=null;this.show('home')},
 login(){this.run=null;$('code').value=this.student||'';$('login-error').textContent='';this.avatarChoice=this.record()?.avatar||0;this.renderAvatars('login-avatars');this.show('login');$('code').focus()},
 renderAvatars(id){$(id).innerHTML=AVATARS.map((a,i)=>`<button type="button" class="avatar-option ${this.avatarChoice===i?'chosen':''}" aria-pressed="${this.avatarChoice===i}" aria-label="${a.name}" onclick="app.pickAvatar(${i},'${id}')"><span>${a.icon}</span><small>${a.name}</small></button>`).join('')},
 pickAvatar(i,target){if(!AVATARS[i])return;this.avatarChoice=i;this.renderAvatars(target);if(target==='change-avatars'){const r=this.record();r.avatar=i;this.save(r);this.dashboard()}},
 avatarDialog(){this.avatarChoice=this.record()?.avatar||0;this.renderAvatars('change-avatars');$('avatar-dialog').showModal()},
 enter(){const code=$('code').value.trim().toUpperCase();if(!this.validCode(code)){$('login-error').textContent='Use 3 a 20 letras, números, hífen ou sublinhado, sem espaços.';return}this.student=code;if(!this.records[code])this.records[code]=this.newRecord(code);else this.records[code].avatar=this.avatarChoice;try{localStorage.setItem(SESSION,code)}catch{}this.save(this.record());this.run=null;this.dashboard()},
 completed(m){return Object.keys(m.answers).length},
 activityCount(r){return r.modules.reduce((n,m)=>n+this.completed(m),0)},
 fullModules(r){return r.modules.filter((m,i)=>this.completed(m)===QBANK.modules[i].items.length).length},
 stars(r,i){const m=r.modules[i];if(this.completed(m)!==QBANK.modules[i].items.length)return 0;const correct=Object.values(m.answers).filter(a=>a.best_correct).length;return correct===6?3:correct>=4?2:1},
 totalStars(r){return r.modules.reduce((n,_,i)=>n+this.stars(r,i),0)},
 starText(n){return `<span class="stars" aria-label="${n} de 3 estrelas">${'★'.repeat(n)}<span class="empty">${'☆'.repeat(3-n)}</span></span>`},
 level(xp){return LEVELS.reduce((n,l,i)=>xp>=l.xp?i:n,0)},
 streak(r){const seen=new Set();let current=0,best=0;r.attempts.filter(t=>t.mode==='module').forEach(t=>{const a=t.answers[0];if(seen.has(a.question_id))return;seen.add(a.question_id);current=a.correct?current+1:0;best=Math.max(best,current)});return{current,best}},
 medals(r){const count=this.activityCount(r),full=this.fullModules(r),streak=this.streak(r).best;return[
  {id:'first',icon:'⌕',name:'Primeira pista',desc:'Conclua uma missão.',on:count>=1},
  {id:'pre',icon:'✎',name:'Ponto de partida',desc:'Entregue as 20 respostas do pré-teste.',on:!!r.diagnostic},
  ...SKILLS.map((s,i)=>({id:'skill'+i,icon:s.icon,name:s.name,desc:'Conclua os seis casos dessa habilidade.',on:this.completed(r.modules[i])===6})),
  {id:'half',icon:'◈',name:'Olhar em expansão',desc:'Conclua três habilidades.',on:full>=3},
  {id:'all',icon:'◇',name:'Investigação completa',desc:'Conclua as seis habilidades.',on:full===6},
  {id:'post',icon:'✓',name:'Desafio final',desc:'Entregue as 20 respostas do pós-teste.',on:!!r.post},
  {id:'survey',icon:'♡',name:'Voz de investigador',desc:'Avalie sua experiência na trilha.',on:!!r.survey},
  {id:'combo3',icon:'↗',name:'Três boas decisões',desc:'Acerte três novas missões seguidas na primeira tentativa.',on:streak>=3},
  {id:'combo6',icon:'✦',name:'Sequência de precisão',desc:'Acerte seis novas missões seguidas na primeira tentativa.',on:streak>=6},
  {id:'post80',icon:'▥',name:'Análise consistente',desc:'Alcance 80% no primeiro pós-teste.',on:!!r.post&&r.post.percentage>=80},
  {id:'stars',icon:'★',name:'Domínio das pistas',desc:'Conquiste as 18 estrelas da trilha.',on:this.totalStars(r)===18}
 ]},
 dashboard(){const r=this.record();if(!r)return this.login();$('student-identity').textContent=r.class_number?'Turma '+r.class_number:'';$('student-current-code').textContent=r.participant_code;this.run=null;const level=this.level(r.xp),next=LEVELS[level+1],stars=this.totalStars(r),activities=this.activityCount(r),done=activities+(r.diagnostic?20:0)+(r.post?20:0)+(r.survey?8:0);
  $('player-avatar').textContent=AVATARS[r.avatar].icon;$('greeting').textContent='Olá, '+(r.full_name||r.participant_code)+'.';$('player-title').textContent=LEVELS[level].name;$('xp').textContent=r.xp+' XP';$('level').textContent=level+1;$('total-stars').textContent=stars+' / 18';$('next-level').textContent=next?'Próximo nível: '+next.name:'Você chegou ao topo da trilha.';$('level-caption').textContent=next?(next.xp-r.xp)+' XP para avançar':'Nível '+(level+1)+' · '+LEVELS[level].name;$('level-bar').style.width=(next?(r.xp-LEVELS[level].xp)/(next.xp-LEVELS[level].xp)*100:100)+'%';
  $('resume').innerHTML=(r.draft?`<div class="resume-card"><div><b>Sua investigação está guardada.</b><p>${r.draft.mode==='module'?'Missão em andamento':(r.draft.mode==='diagnostic'?'Pré-teste':'Pós-teste')+' · '+r.draft.answers.filter(Boolean).length+'/20 respondidas'}</p></div><button class="btn" onclick="app.resume()">Continuar →</button></div>`:'')+(!this.storageOK?'<div class="notice">O navegador não está guardando os dados. Baixe uma cópia do progresso antes de fechar.</div>':'');
  $('assessment-before').innerHTML=this.assessment('diagnostic','Pré-teste: seu ponto de partida',r.diagnostic?`${r.diagnostic.score}/20 acertos · resultado inicial preservado`:'20 casos · gabarito ao entregar · até 200 XP',!!r.diagnostic,true);
  $('steps').innerHTML=SKILLS.map((s,i)=>{const n=this.completed(r.modules[i]),st=this.stars(r,i);return `<article class="skill-card ${!r.diagnostic?'locked':''}" style="${style(s)}"><div class="skill-card-top"><span class="skill-icon">${s.icon}</span><div><span class="kicker">HABILIDADE ${i+1}</span><h3>${esc(s.name)}</h3></div>${this.starText(st)}</div><div class="skill-card-body"><p>${esc(s.intro)}</p><div class="progress"><i style="width:${n/6*100}%"></i></div><div class="skill-card-status"><span>${n}/6 casos concluídos</span><span>${r.modules[i].xp}/600 XP</span></div><button class="btn" onclick="app.module(${i})" ${!r.diagnostic?'disabled':''}>${!r.diagnostic?'Conclua o pré-teste para abrir':n===6?'Revisar e aperfeiçoar →':'Investigar os casos →'}</button></div></article>`}).join('');
  $('assessment-after').innerHTML=this.assessment('post','Pós-teste: a prova final',r.post?`${r.post.score}/20 acertos · resultado inicial preservado`:'20 novos casos · liberado após os 36 desafios',!!r.post,this.fullModules(r)===6)+`<article class="assessment"><span class="assessment-icon">♡</span><div><h3>Sua experiência</h3><p>${r.survey?'Avaliação registrada · você pode rever':'Oito frases sobre a trilha, sem certo ou errado'}</p></div><button class="btn secondary" onclick="app.survey()" ${!r.post?'disabled':''}>${r.survey?'Rever avaliação':'Avaliar a trilha'}</button></article>`;
  $('streak-count').textContent=this.streak(r).current+' '+(this.streak(r).current===1?'acerto':'acertos');$('mini-medals').innerHTML=this.medals(r).map(m=>`<span class="mini-medal ${m.on?'':'off'}" title="${esc(m.name)}: ${esc(m.desc)}" aria-label="${esc(m.name)}: ${m.on?'conquistada':'pendente'}">${m.icon}</span>`).join('');const pct=Math.round(done/84*100);$('pct').textContent=pct+'%';$('bar').style.width=pct+'%';$('progress-detail').textContent=activities+'/36 missões · '+(r.diagnostic&&r.post?'2':r.diagnostic?'1':'0')+'/2 testes · '+(r.survey?'avaliação concluída':'avaliação pendente');this.show('dashboard');
 },
 assessment(mode,title,text,done,unlocked){return `<article class="assessment"><span class="assessment-icon">${done?'✓':'✎'}</span><div><h3>${title}</h3><p>${text}</p></div><button class="btn ${done?'secondary':'primary'}" onclick="app.${done?'viewExam':'startQuiz'}('${mode}')" ${!unlocked?'disabled':''}>${done?'Ver resultado':'Começar prova →'}</button>${done?`<button class="back" onclick="app.startQuiz('${mode}')">Treinar novamente</button>`:''}</article>`},
 module(i){const r=this.record();if(!r?.diagnostic)return this.toast('Conclua o pré-teste para liberar as missões.');if(!QBANK.modules[i])return;this.run=null;this.moduleIndex=i;const m=QBANK.modules[i],p=r.modules[i];$('module-banner').style.cssText=style(m);$('module-banner').innerHTML=`<div class="module-title"><span class="skill-icon">${m.icon}</span><div><span class="eyebrow">HABILIDADE ${i+1} · SEIS CASOS</span><h1>${esc(m.name)}</h1><p>${esc(m.intro)}</p></div></div><div class="module-badges">${this.starText(this.stars(r,i))}<small>${p.xp}/600 XP conquistados</small></div>`;$('lesson-list').innerHTML=m.lesson.map(l=>'<li>'+esc(l)+'</li>').join('');$('module-count').textContent=this.completed(p)+'/6';$('module-bar').style.width=this.completed(p)/6*100+'%';$('module-star-hint').textContent='★ Complete os 6 casos · ★★ Acerte ao menos 4 · ★★★ Acerte todos. Você pode revisar os erros; o melhor resultado de cada caso é mantido.';
  $('missions').innerHTML=m.items.map((q,j)=>{const a=p.answers[q.id];return `<article class="mission-card" style="${style(m)}"><div class="mission-thumb"><img src="${q.image}" alt="Tela simulada de ${esc(q.scene.app)} do caso ${esc(q.title)}" loading="lazy"></div><div class="mission-body"><div class="mission-label"><span>CASO ${String(j+1).padStart(2,'0')}</span><b>${a?a.best_correct?'✓ Acerto registrado':'↺ Pode aperfeiçoar':'Até 100 XP'}</b></div><h3>${esc(q.title)}</h3><p>${esc(q.prompt)}</p><button class="btn ${a?'secondary':'primary'}" onclick="app.startItem(${i},${j})">${a?'Reinvestigar o caso':'Abrir investigação →'}</button></div></article>`}).join('');this.show('module');
 },
 async begin(run){const r=this.record();if(r.draft){if(r.draft.mode===run.mode&&r.draft.ids.join()===run.ids.join())return this.resume();if(!confirm('Há uma atividade não entregue. Começar esta investigação substituirá apenas esse rascunho. Os resultados concluídos serão mantidos. Continuar?'))return}this.run=run;r.draft=clone(run);this.save(r);this.show('quiz');this.renderQuestion()},
 makeRun(mode,mi=null,ids){return{mode,mi,ids,index:0,answers:Array(ids.length).fill(null),flags:Array(ids.length).fill(false),started_at:new Date().toISOString()}},
 startItem(mi,qi){if(!this.record()?.diagnostic)return this.toast('Conclua o pré-teste primeiro.');const q=QBANK.modules[mi]?.items[qi];if(!q)return;this.begin(this.makeRun('module',mi,[q.id]))},
 startQuiz(mode){if(!['diagnostic','post'].includes(mode))return;const r=this.record();if(!r)return this.login();if(mode==='post'&&this.fullModules(r)!==6)return this.toast('Conclua os 36 casos para liberar o pós-teste.');if(r.draft?.mode===mode)return this.resume();this.pendingMode=mode;$('exam-intro-title').textContent=mode==='diagnostic'?'Seu ponto de partida.':'A prova final.';$('exam-intro-note').textContent=r[mode]?'Treino: o primeiro resultado será mantido e esta tentativa não gerará XP adicional.':'Seu primeiro resultado será registrado. Cada acerto vale 10 XP. O objetivo é avaliar suas decisões com as pistas dos casos.';$('exam-intro').showModal()},
 beginExam(){const mode=this.pendingMode;if(!['diagnostic','post'].includes(mode))return;$('exam-intro').close();this.pendingMode=null;this.begin(this.makeRun(mode,null,QBANK[mode].map(q=>q.id)))},
 resume(){const r=this.record();if(!r?.draft)return;this.run=clone(r.draft);this.show('quiz');this.renderQuestion()},
 isExam(){return !!this.run&&this.run.mode!=='module'},
 saveDraft(){const r=this.record();r.draft=clone(this.run);this.save(r)},
 renderQuestion(){const run=this.run;if(!run)return;const q=QUESTION_BY_ID[run.ids[run.index]],a=run.answers[run.index],exam=this.isExam();$('quiz-mode').textContent=exam?run.mode==='diagnostic'?'PRÉ-TESTE':'PÓS-TESTE':'MISSÃO · '+SKILLS[q.skill].name;$('quiz-count').textContent=(run.index+1)+' / '+run.ids.length;$('quiz-bar').style.width=run.answers.filter(Boolean).length/run.ids.length*100+'%';$('case-content').innerHTML=Scenes.render(q.scene);$('case-transcript').textContent=Scenes.text(q.scene);document.querySelector('.transcript').open=false;const panel=document.querySelector('.question-panel');panel.style.cssText=style(SKILLS[q.skill]);$('question-tag').textContent=q.tag;$('question-title').textContent=q.title;$('question-text').textContent=q.prompt;$('choose-hint').textContent=exam?'Escolha uma alternativa. Você pode mudar sua resposta antes da entrega.':'Escolha uma alternativa com base nas pistas do caso.';
  $('answers').innerHTML=q.o.map((o,i)=>`<button class="answer ${a?.selected===i?'selected':''}" onclick="app.choose(${i})" aria-pressed="${a?.selected===i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('');$('feedback').className='feedback hidden';$('feedback').innerHTML='';['exam-banner','exam-navigation','flag-row','review-button'].forEach(id=>$(id).classList.toggle('hidden',!exam));$('previous').classList.toggle('hidden',!exam);$('previous').disabled=run.index===0;$('next').disabled=!exam&&!a;$('next').textContent=exam?run.index===run.ids.length-1?'Revisar e entregar ✓':'Próxima →':'Concluir caso ✓';$('xp-hint').textContent=exam?this.record()[run.mode]?'Treino: sua pontuação inicial será preservada.':'Resultado e XP calculados somente depois da entrega.':'25 XP ao concluir · 100 XP ao acertar · cada caso vale no máximo 100 XP.';
  if(exam){this.renderNavigation();this.updateFlag()}else if(a)this.showFeedback(a);
 },
 renderNavigation(){const run=this.run;const count=run.answers.filter(Boolean).length;$('exam-status').textContent=count+'/'+run.ids.length+' respondidas';$('question-map').innerHTML=this.navigationHTML(run)},
 navigationHTML(run,review=false){return run.ids.map((_,i)=>`<button class="qnav ${run.answers[i]?'answered':''} ${run.flags[i]?'flagged':''} ${i===run.index?'current':''}" onclick="app.jump(${i},${review})" aria-label="Questão ${i+1}, ${run.answers[i]?'respondida':'sem resposta'}${run.flags[i]?', marcada para revisar':''}" ${i===run.index?'aria-current="step"':''}>${i+1}</button>`).join('')},
 choose(i){const run=this.run;if(!run||!Number.isInteger(i)||i<0||i>3)return;if(!this.isExam()&&run.answers[run.index])return;const q=QUESTION_BY_ID[run.ids[run.index]];run.answers[run.index]={question_id:q.id,selected:i,correct:i===q.a,at:new Date().toISOString()};this.saveDraft();if(this.isExam()){document.querySelectorAll('.answer').forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-pressed',String(j===i))});this.renderNavigation();$('quiz-bar').style.width=run.answers.filter(Boolean).length/run.ids.length*100+'%'}else{this.showFeedback(run.answers[run.index]);this.playSound(run.answers[run.index].correct?'correct':'select')}},
 showFeedback(a){const q=QUESTION_BY_ID[a.question_id];document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;b.classList.remove('selected');if(i===q.a)b.classList.add('correct');if(i===a.selected&&i!==q.a)b.classList.add('wrong');b.setAttribute('aria-label',q.o[i]+(i===a.selected?'. Sua resposta.':'')+(i===q.a?'. Resposta correta.':''))});$('feedback').className='feedback '+(a.correct?'good':'bad');$('feedback').innerHTML='<b>'+(a.correct?'✓ Decisão bem fundamentada.':'↺ Compare as pistas e reveja o raciocínio.')+'</b>'+esc(q.e);$('next').disabled=false},
 flag(){if(!this.isExam())return;this.run.flags[this.run.index]=!this.run.flags[this.run.index];this.saveDraft();this.updateFlag();this.renderNavigation()},
 updateFlag(){const flagged=this.run.flags[this.run.index];$('flag-button').setAttribute('aria-pressed',String(flagged));$('flag-button').textContent=flagged?'⚑ Marcada para revisar':'⚑ Marcar para revisar'},
 jump(i,close=false){if(!this.isExam()||!Number.isInteger(i)||i<0||i>=this.run.ids.length)return;if(close)$('exam-review').close();this.run.index=i;this.saveDraft();this.renderQuestion();this.focusQuestion()},
 focusQuestion(){const behavior=matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';$('quiz').scrollIntoView({behavior,block:'start'})},
 previous(){if(this.isExam()&&this.run.index>0)this.jump(this.run.index-1)},
 next(){if(!this.run)return;if(this.isExam()){if(this.run.index<this.run.ids.length-1)this.jump(this.run.index+1);else this.reviewExam()}else if(this.run.answers[0])this.finish()},
 reviewExam(){if(!this.isExam())return;const run=this.run,count=run.answers.filter(Boolean).length,flags=run.flags.filter(Boolean).length;$('review-summary').textContent=count+'/20 respondidas · '+flags+' marcada'+(flags===1?'':'s')+' para revisar.';$('review-map').innerHTML=this.navigationHTML(run,true);$('review-alert').textContent=count<20?'Faltam '+(20-count)+' respostas. Abra as questões sem resposta antes de entregar.':flags?'Todas respondidas. Há itens marcados para revisar; você pode voltar a eles ou entregar suas respostas.':'Todas respondidas. Confira suas escolhas: depois da entrega, esta tentativa ficará registrada.';$('submit-exam').disabled=count<20;$('exam-review').showModal()},
 submitExam(){if(!this.isExam()||this.run.answers.some(a=>!a))return;$('exam-review').close();this.finish()},
 exitQuiz(){if(this.run)this.saveDraft();this.run=null;this.dashboard();this.toast(this.storageOK?'Rascunho salvo. Você pode continuar depois.':'Rascunho disponível nesta sessão. Baixe uma cópia para guardar.')},
 zoomCase(){if(!this.run)return;const q=QUESTION_BY_ID[this.run.ids[this.run.index]];$('image-title').textContent=q.title;$('case-image').src=q.image;$('case-image').alt=Scenes.text(q.scene);$('image-dialog').showModal()},
 readQuestion(){if(!this.run)return;if(!window.speechSynthesis)return this.toast('Este navegador não oferece leitura em voz alta.');const q=QUESTION_BY_ID[this.run.ids[this.run.index]];window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(Scenes.text(q.scene)+'. '+q.prompt+'. '+q.o.map((o,i)=>String.fromCharCode(65+i)+'. '+o).join('. '));u.lang='pt-BR';u.rate=.92;window.speechSynthesis.speak(u)},
 finish(){if(this.finishing||!this.run||this.run.answers.some(a=>!a))return;this.finishing=true;const run=clone(this.run),r=this.record(),now=new Date().toISOString(),beforeLevel=this.level(r.xp),beforeMedals=new Set(this.medals(r).filter…3275 tokens truncated…a não registrada.</p>');if(r.draft){const d=r.draft;$('teacher-details').innerHTML+='<h3>Atividade em andamento</h3><p>'+(d.mode==='module'?'Missão':d.mode==='diagnostic'?'Pré-teste':'Pós-teste')+' · '+d.answers.filter(Boolean).length+'/'+d.ids.length+' respondidas · questão '+(d.index+1)+'</p>'+d.answers.filter(Boolean).map(a=>'<p>'+esc(QUESTION_BY_ID[a.question_id].title)+': <b>'+String.fromCharCode(65+a.selected)+'</b></p>').join('')}$('teacher-details').classList.remove('hidden');$('teacher-details').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},
 exportCSV(){const rows=Object.values(this.records);if(!rows.length)return this.toast('Não há resultados para exportar.');download('midiacheck_resultados.csv',csv([['nome','turma','codigo','pre_acertos','pre_total','pre_pct','pos_acertos','pos_total','pos_pct','diferenca_questoes','diferenca_pontos_percentuais','xp','nivel','estrelas','habilidades_completas','casos_concluidos',...SKILLS.map((_,i)=>'habilidade_'+(i+1)+'_melhores_acertos'),'percepcao_media',...SURVEY.map((_,i)=>'percepcao_'+(i+1)),'atualizado_em'],...rows.map(r=>[r.full_name||'',r.class_number||'',r.participant_code,r.diagnostic?.score,r.diagnostic?.total,r.diagnostic?.percentage,r.post?.score,r.post?.total,r.post?.percentage,r.post&&r.diagnostic?r.post.score-r.diagnostic.score:'',r.post&&r.diagnostic?r.post.percentage-r.diagnostic.percentage:'',r.xp,this.level(r.xp)+1,this.totalStars(r),this.fullModules(r),this.activityCount(r),...r.modules.map(m=>Object.values(m.answers).filter(a=>a.best_correct).length),r.survey?.average,...(r.survey?.answers||Array(8).fill('')),r.updated_at])]),'text/csv;charset=utf-8');this.toast('Resultados exportados.')},
 exportAnswers(){const rows=[];for(const r of Object.values(this.records)){r.attempts.forEach((t,i)=>t.answers.forEach(a=>{const q=QUESTION_BY_ID[a.question_id];rows.push([r.participant_code,t.mode,t.mi===null?'':t.mi+1,i+1,t.practice?'sim':'nao',q.id,q.tag,q.title,q.prompt,Scenes.text(q.scene),String.fromCharCode(65+a.selected),q.o[a.selected],a.correct?1:0,String.fromCharCode(65+q.a),q.o[q.a],q.e,t.started_at,t.at,a.at])}));if(r.survey)r.survey.answers.forEach((v,i)=>rows.push([r.participant_code,'percepcao','',1,'nao','s'+(i+1),'Experiência','',SURVEY[i],'',v,labels[v-1],'','','','',r.survey.at,r.survey.at,r.survey.at]))}if(!rows.length)return this.toast('Não há respostas concluídas para exportar.');download('midiacheck_respostas.csv',csv([['codigo','etapa','habilidade','tentativa','treino','questao_id','competencia','titulo_caso','pergunta','material_do_caso','alternativa','resposta','acerto','gabarito','resposta_correta','explicacao','inicio_tentativa','entrega_tentativa','resposta_em'],...rows]),'text/csv;charset=utf-8');this.toast('Respostas exportadas.')},
 backup(){download('midiacheck_progresso.json',JSON.stringify({dataset:DATASET,schema:1,exported_at:new Date().toISOString(),records:this.records},null,2),'application/json');this.toast('Cópia do progresso baixada.')},
 validRecord(r){
  const obj=o=>o&&typeof o==='object'&&!Array.isArray(o),date=s=>typeof s==='string'&&s.length<60&&Number.isFinite(Date.parse(s));
  const answer=a=>obj(a)&&QUESTION_BY_ID[a.question_id]&&Number.isInteger(a.selected)&&a.selected>=0&&a.selected<4&&a.correct===(a.selected===QUESTION_BY_ID[a.question_id].a)&&date(a.at);
  const same=(a,b)=>a.question_id===b.question_id&&a.selected===b.selected&&a.correct===b.correct&&a.at===b.at;
  const test=(t,mode)=>t===null||(obj(t)&&t.total===QBANK[mode].length&&Array.isArray(t.answers)&&t.answers.length===t.total&&t.answers.every((a,i)=>answer(a)&&a.question_id===QBANK[mode][i].id)&&t.score===t.answers.filter(a=>a.correct).length&&t.percentage===Math.round(t.score/t.total*100)&&date(t.at));
  if(!obj(r)||!this.validCode(r.participant_code)||!date(r.updated_at)||!Number.isInteger(r.avatar)||r.avatar<0||r.avatar>3||!test(r.diagnostic,'diagnostic')||!test(r.post,'post')||!Array.isArray(r.modules)||r.modules.length!==6||!Number.isInteger(r.xp)||r.xp<0||r.xp>4000||!Array.isArray(r.attempts)||r.attempts.length>10000)return false;
  let mxp=0;for(let i=0;i<6;i++){const m=r.modules[i];if(!obj(m)||!obj(m.answers))return false;let sum=0;for(const [id,a]of Object.entries(m.answers)){if(!QBANK.modules[i].items.some(q=>q.id===id)||id!==a?.question_id||!answer(a)||typeof a.best_correct!=='boolean'||(a.correct&&!a.best_correct)||a.xp!==(a.best_correct?100:25)||!Number.isInteger(a.attempts)||a.attempts<1)return false;sum+=a.xp}if(m.xp!==sum)return false;mxp+=sum}
  if(r.xp!==mxp+(r.diagnostic?.score||0)*10+(r.post?.score||0)*10)return false;
  if((mxp>0&&!r.diagnostic)||(r.post&&(!r.diagnostic||this.fullModules(r)!==6)))return false;
  if(r.survey!==null&&(!r.post||!obj(r.survey)||!Array.isArray(r.survey.answers)||r.survey.answers.length!==8||!r.survey.answers.every(v=>Number.isInteger(v)&&v>=1&&v<=5)||r.survey.average!==r.survey.answers.reduce((n,v)=>n+v,0)/8||!date(r.survey.at)))return false;
  if(r.survey_draft!==undefined&&(!r.post||!Array.isArray(r.survey_draft)||r.survey_draft.length!==8||!r.survey_draft.every(v=>Number.isInteger(v)&&v>=0&&v<=5)))return false;
  const histories={},tests={diagnostic:[],post:[]};
  for(const t of r.attempts){if(!obj(t)||!['diagnostic','post','module'].includes(t.mode)||typeof t.practice!=='boolean'||!date(t.at)||!date(t.started_at)||!Array.isArray(t.answers)||!t.answers.every(answer))return false;if(t.mode==='module'){if(t.practice||!Number.isInteger(t.mi)||t.mi<0||t.mi>5||t.answers.length!==1||!QBANK.modules[t.mi].items.some(q=>q.id===t.answers[0].question_id))return false;const a=t.answers[0];(histories[a.question_id]||=([])).push(a)}else{if(t.mi!==null||t.answers.length!==QBANK[t.mode].length||!t.answers.every((a,i)=>a.question_id===QBANK[t.mode][i].id)||t.practice!==(tests[t.mode].length>0))return false;tests[t.mode].push(t)}}
  for(const mode of ['diagnostic','post']){const t=tests[mode][0];if(!!t!==!!r[mode])return false;if(t&&(t.at!==r[mode].at||!t.answers.every((a,i)=>same(a,r[mode].answers[i]))))return false}
  const completedIds=r.modules.flatMap(m=>Object.keys(m.answers));if(Object.keys(histories).length!==completedIds.length)return false;for(const m of r.modules)for(const [id,a]of Object.entries(m.answers)){const h=histories[id];if(!h||a.attempts!==h.length||a.best_correct!==h.some(a=>a.correct)||!same(a,h[h.length-1]))return false}
  if(r.draft!==null){const d=r.draft;if(!obj(d)||!['diagnostic','post','module'].includes(d.mode)||!Array.isArray(d.ids)||!Array.isArray(d.answers)||!Array.isArray(d.flags)||d.flags.length!==d.ids.length||!d.flags.every(f=>typeof f==='boolean')||d.answers.length!==d.ids.length||!date(d.started_at)||!Number.isInteger(d.index)||d.index<0||d.index>=d.ids.length||!d.answers.every((a,i)=>a===null||(answer(a)&&a.question_id===d.ids[i])))return false;if(d.mode==='module'){if(!r.diagnostic||!Number.isInteger(d.mi)||d.mi<0||d.mi>5||d.ids.length!==1||d.flags[0]||!QBANK.modules[d.mi].items.some(q=>q.id===d.ids[0]))return false}else if(d.mi!==null||d.ids.join()!==QBANK[d.mode].map(q=>q.id).join()||(d.mode==='post'&&this.fullModules(r)!==6))return false}
  return true;
 },
 async restore(event){const file=event.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('size');const data=JSON.parse(await file.text());if(data.dataset!==DATASET||data.schema!==1||!data.records||typeof data.records!=='object'||Array.isArray(data.records)||!Object.entries(data.records).every(([k,r])=>k===r.participant_code&&this.validRecord(r)))throw Error('shape');const count=Object.keys(data.records).length;if(!count)throw Error('empty');if(!confirm('Restaurar '+count+' participante(s)? Códigos já existentes serão substituídos pelos dados do arquivo. Os demais serão mantidos.'))return;Object.assign(this.records,data.records);this.storageOK=true;this.run=null;this.persist();this.teacher();this.toast(this.storageOK?'Progresso restaurado.':'Dados abertos nesta sessão. O navegador não conseguiu guardar; baixe uma cópia antes de fechar.')}catch{this.toast('Arquivo inválido ou incompatível. Use uma cópia exportada por este pacote, com até 10 MB.')}finally{event.target.value=''}}
});
window.addEventListener('DOMContentLoaded',()=>app.init());
